name: Update Docker Image
run-name: ${{ github.actor }} pushed content to be updated in docker image
on:
  push:
    branches: [release]

jobs:
  Update-Docker-Image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Update docker image
        run: |
          docker build --no-cache -t zeznjt/order-matcher-frontend .
          docker push zeznjt/order-matcher-frontend
